# Lectures

[Zoom Link for the Live Lecture](https://uwmadison.zoom.us/j/94005146127?pwd=obHy3MRaU409nQtDHu5dHFZVIsOeXD.1).

### Week 1: Introduction to Computation and Julia

- **Lecture 1:** Intro to Computation and Basic Julia
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture1.pdf)
  - [Code-along](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong1.jl)
  - [Recording](https://uwmadison.zoom.us/rec/share/ynn8lvn74Gl4zZaJQ_tQmhVo3pvyLBMaE98E2HVagWL1Kmb2lJhFdVikDxDjJYSu.ELFWtDc2BCCN0jRu 
Passcode:N#u3=Es#) (Passcode: N#u3=Es#)

- **Lecture 2:** Performance Optimization and Advanced Julia
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture2.pdf)
  - [Code-along](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong2.jl)
  - [Recording](https://uwmadison.zoom.us/rec/share/6ezG063zaKlhNXcFdC8hrTrqcq5e1fP2vVUQqfVjwJk8JoSyvb3gxHeMjcSTtERy.VGdbaLZOycmGeTBR?startTime=1718819966000
Passcode: WdTY%6X3) (Passcode: WdTY%6X3)

- [Homework 1:](https://johnfhiggins.github.io/ComputationalBootcamp/homeworks/homework1.html) Due Wednesday July 26. 
  - Submit Link: https://classroom.github.com/a/ltOWDjoe
  
### Week 2: Numeric Methods

- **Lecture 3:** Numeric Optimization 
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture3.pdf)
  - [Code-along](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong3.jl)
  - [Recording](https://uwmadison.zoom.us/rec/share/jYcm3SOBsnEj06FwHa2m2Jek2hr73QkmxMQXgo8Ry4vMtqCzczYCwKV0kxxmk1or.Ih-2Up-8199PViCW 
Passcode: e^=7teO9)(Passcode: e^=7teO9)
- **Lecture 4:** Interpolation
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture4.pdf)
  - [Code-along](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong4.jl)


- [Homework 2:](https://johnfhiggins.github.io/ComputationalBootcamp/homeworks/homework2.html) Due Wednesday July 3. 
    - Submit Link: https://classroom.github.com/a/_scR5Vb7

### Week 3: Advanced Topics

- **Lecture 5:** Numeric Integration
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture5.pdf)
  - [Code-along](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong5.jl)

- **Lecture 6:** Parallelization and UW Resources
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture6.pdf)
  - [Code-along](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong6.jl)

- [Homework 3:](https://johnfhiggins.github.io/ComputationalBootcamp/homeworks/homework3.html) Due Wednesday July 10. 
    - Submit Link: https://classroom.github.com/a/7-WWUk4Q

### Week 4: Dynamic Programming

- **Lecture 7:** Dynamic Programming
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture7.pdf)
  - [Code-along](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong7.jl)

- **Lecture 8:** Economic Applications
  - [Slides](https://johnfhiggins.github.io/ComputationalBootcamp/lectures/lecture8.pdf)
  - [Code-along master.jl](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong8_master.jl)
  - [Code-along functions.jl](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong8_functions.jl)
  - [Code-along structs.jl](https://johnfhiggins.github.io/ComputationalBootcamp/codealongs/CodeAlong8_structs.jl)

- [Homework 4:](https://johnfhiggins.github.io/ComputationalBootcamp/homeworks/homework4.html) Due Wednesday July 17. 
  - Submit Link:https://classroom.github.com/a/4CBmQTaW


  